version: '3.8'

services:
  telegram-spybot:
    container_name: telegram-spybot
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - media-volume:/app/media
      - db-volume:/app
    environment:
      - TOKEN=${TOKEN}
      - USER_ID=${USER_ID}
      - MESSAGES_LIFETIME=${MESSAGES_LIFETIME:-24}
      - CLEANUP_INTERVAL=${CLEANUP_INTERVAL:-3600}

volumes:
  media-volume:
    name: telegram-spybot-media
  db-volume:
    name: telegram-spybot-db
