version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-spybot
    volumes:
      - ./media:/app/media
      - ./messages.db:/app/messages.db
    env_file:
      - .env
    restart: unless-stopped